# MkDocs configuration for NMR Pulse Sequence Repository
site_name: NMR Pulse Sequence Repository
site_description: Community-driven repository for sharing and documenting NMR pulse sequences
site_url: https://waudbygroup.github.io/pulseprograms/
repo_url: https://github.com/waudbygroup/pulseprograms
repo_name: waudbygroup/pulseprograms

theme:
  name: material
  icon:
    logo: material/magnet-on
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme)"
      primary: orange
      accent: orange
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: orange
      accent: orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: orange
      accent: orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - toc.follow
    - content.code.copy

plugins:
  - search
  - tags

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - tables
  - footnotes
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
  - Home: index.md
  - Getting Started:
    - Quick Start: getting-started/quickstart.md
    # - Installation: getting-started/installation.md
    # - Basic Usage: getting-started/usage.md
  # - Sequences: sequences/index.md
  - Sequence Database: database/
  - Contributing: contributing/index.md
  # - Contributing:
    # - Overview: contributing/index.md
    # - Low Barrier: contributing/low-barrier.md
    # - Medium Barrier: contributing/medium-barrier.md
    # - High Barrier: contributing/high-barrier.md
    # - Review Process: contributing/review.md
  - Annotation Schema:
    - Current Schema: schema/current.md
    - Field Reference: schema/fields.md
  # - Community:
  #   - Guidelines: community/guidelines.md
  #   - Recognition: community/recognition.md
  #   - Discussions: community/discussions.md
  # - Technical:
  #   - GitHub Actions: technical/github-actions.md
  #   - API Reference: technical/api.md
  #   - Development: technical/development.md

extra:
  social:
    - icon: material/github
      link: https://github.com/waudbygroup/pulseprograms
  version:
    provider: mike