name: Documentation Generation

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Full history for Git-based changelogs

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyyaml mkdocs mkdocs-material mkdocs-git-revision-date-localized-plugin
        pip install pygments

    - name: Prepare documentation build
      run: |
        # Create proper directory structure
        mkdir -p docs-generated/docs
        # Copy existing docs content to docs subdirectory
        cp -r docs/* docs-generated/docs/
        # Copy mkdocs.yml to the parent directory
        cp docs/mkdocs.yml docs-generated/
        # Ensure sequence and schema directories exist for generated content
        mkdir -p docs-generated/docs/sequences
        mkdir -p docs-generated/docs/schema

    - name: Generate dynamic content
      run: |
        # Generate sequence database and individual sequence pages
        python .github/scripts/generate_docs.py
        # Generate schema documentation
        python .github/scripts/generate_schema_docs.py

    - name: Setup Pages
      uses: actions/configure-pages@v3

    - name: Build with MkDocs
      run: |
        cd docs-generated
        mkdocs build --clean

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: docs-generated/build

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4